document.write('<script src="/js/jquery.min.js"></script>');
document.write('<script src="/js/angular.min.js"></script>');
document.write('<script src="/js/bootstrap.min.js"></script>');
document.write('<script src="/js/main.js"></script>');
document.write('<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"/>');
document.write('<link href="/css/font-awesome.min.css" rel="stylesheet"/>');
document.write('<link href="/css/bootstrap.min.css" rel="stylesheet"/>');
document.write('<link href="/css/main.css" rel="stylesheet" type="text/css"/>');
document.write('<link rel="icon" href="/img/icon.png"/>');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">');